{
    "openapi": "3.0.0",
    "info": {
        "title": "My Documentation",
        "description": "Aplicação para cadastro de notas",
        "version": "1.0.0"
    },
    "paths": {
        "\/pessoas": {
            "post": {
                "tags": [
                    "Pessoas"
                ],
                "summary": "Create a Pessoa.",
                "description": "Create a Pessoa.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/PessoaCreate"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Pessoa created",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/PessoaCreate"
                                    },
                                    "example": {
                                        "nome": "Gabriel Velezmoro",
                                        "nomeMae": "nome mae",
                                        "nomePai": "nome pai",
                                        "cep": "88790000",
                                        "dataNascimento": "02-07-1997"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Pessoa already created"
                    }
                }
            },
            "put": {
                "tags": [
                    "Pessoas"
                ],
                "summary": "Update a Pessoa.",
                "description": "Update a Pessoa.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/PessoaUpdate"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Pessoa updated",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/PessoaUpdate"
                                    },
                                    "example": {
                                        "id": 5,
                                        "nome": "Gabriel Velezmoro",
                                        "nomeMae": "nome mae",
                                        "nomePai": "nome pai",
                                        "cep": "88790000",
                                        "dataNascimento": "1997-02-07T02:00:00.000Z",
                                        "dataCadastro": "2023-04-29T03:00:00.000Z",
                                        "dataEdicao": "2023-04-29T03:00:00.000Z"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/pessoas\/list": {
            "post": {
                "tags": [
                    "Pessoas"
                ],
                "summary": "List all Pessoas.",
                "description": "List all Pessoas.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/PessoaList"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/PessoaList"
                                    },
                                    "example": [
                                        {
                                            "id": 5,
                                            "nome": "Gabriel Velezmoro",
                                            "nomeMae": "nome mae",
                                            "nomePai": "nome pai",
                                            "cep": "88790000",
                                            "dataNascimento": "1997-02-07T02:00:00.000Z",
                                            "dataCadastro": "2023-04-29T03:00:00.000Z",
                                            "dataEdicao": "2023-04-29T03:00:00.000Z"
                                        },
                                        {
                                            "id": 6,
                                            "nome": "Gabriel Velezmoro",
                                            "nomeMae": "nome mae",
                                            "nomePai": "nome pai",
                                            "cep": "88790000",
                                            "dataNascimento": "1997-02-07T02:00:00.000Z",
                                            "dataCadastro": "2023-04-29T03:00:00.000Z",
                                            "dataEdicao": "2023-04-29T03:00:00.000Z"
                                        },
                                        {
                                            "id": 7,
                                            "nome": "Gabriel Velezmoro",
                                            "nomeMae": "nome mae",
                                            "nomePai": "nome pai",
                                            "cep": "88790000",
                                            "dataNascimento": "1997-02-07T02:00:00.000Z",
                                            "dataCadastro": "2023-04-29T03:00:00.000Z",
                                            "dataEdicao": "2023-04-29T03:00:00.000Z"
                                        },
                                        {
                                            "id": 8,
                                            "nome": "Gabriel Velezmoro",
                                            "nomeMae": "nome mae",
                                            "nomePai": "nome pai",
                                            "cep": "88790000",
                                            "dataNascimento": "1997-02-07T02:00:00.000Z",
                                            "dataCadastro": "2023-04-29T03:00:00.000Z",
                                            "dataEdicao": "2023-04-29T03:00:00.000Z"
                                        },
                                        {
                                            "id": 2,
                                            "nome": "Gabriel Velezmoro",
                                            "nomeMae": "nome mae",
                                            "nomePai": "nome pai",
                                            "cep": "88790000",
                                            "dataNascimento": "1997-02-07T02:00:00.000Z",
                                            "dataCadastro": "2023-04-28T03:00:00.000Z",
                                            "dataEdicao": "2023-04-29T03:00:00.000Z"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/pessoas\/{id}": {
            "get": {
                "tags": [
                    "Pessoas"
                ],
                "summary": "Return a Pessoa.",
                "description": "Return a single record of Pessoa.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Pessoa id.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/PessoaGet"
                                    },
                                    "example": {
                                        "id": 5,
                                        "nome": "Gabriel Velezmoro",
                                        "nomeMae": "nome mae",
                                        "nomePai": "nome pai",
                                        "cep": "88790000",
                                        "dataNascimento": "1997-02-07T02:00:00.000Z",
                                        "dataCadastro": "2023-04-29T03:00:00.000Z",
                                        "dataEdicao": "2023-04-29T03:00:00.000Z",
                                        "localizacao": {
                                            "cep": "88790-000",
                                            "logradouro": "",
                                            "complemento": "",
                                            "bairro": "",
                                            "localidade": "Laguna",
                                            "uf": "SC",
                                            "ibge": "4209409",
                                            "gia": "",
                                            "ddd": "48",
                                            "siafi": "8185"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Pessoas"
                ],
                "summary": "Delete a Pessoa.",
                "description": "Delete a single record of Pessoa.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Pessoa id.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/PessoaGet"
                                    },
                                    "example": {
                                        "id": 5,
                                        "nome": "Gabriel Velezmoro",
                                        "nomeMae": "nome mae",
                                        "nomePai": "nome pai",
                                        "cep": "88790000",
                                        "dataNascimento": "1997-02-07T02:00:00.000Z",
                                        "dataCadastro": "2023-04-29T03:00:00.000Z",
                                        "dataEdicao": "2023-04-29T03:00:00.000Z"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/notas": {
            "post": {
                "tags": [
                    "Notas"
                ],
                "summary": "Create a Nota.",
                "description": "Create a Nota.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/NotaCreate"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Nota created",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/NotaCreate"
                                    },
                                    "example": {
                                        "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                                        "state_id": "8f019a6b-cd1e-46e4-b1f6-a7b810a065ea",
                                        "name": "Nome de nota"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Nota already created"
                    }
                }
            },
            "put": {
                "tags": [
                    "Notas"
                ],
                "summary": "Update a Nota.",
                "description": "Update a Nota.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/NotaUpdate"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Nota updated",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/NotaUpdate"
                                    },
                                    "example": {
                                        "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                                        "state_id": "f22683d6-6e11-428d-9d01-d979101eb036",
                                        "name": "Nome de nota"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/notas\/list": {
            "post": {
                "tags": [
                    "Notas"
                ],
                "summary": "List all Notas.",
                "description": "List all Notas.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application\/json": {
                            "schema": {
                                "$ref": "#\/components\/schemas\/NotaList"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/NotaList"
                                    },
                                    "example": [
                                        {
                                            "id": "04450d12-ae57-4dea-954e-43e014878612",
                                            "state_id": "2df9a958-e7cb-4656-9ce2-3b8fe47168cf",
                                            "name": "Nome de nota 1"
                                        },
                                        {
                                            "id": "761fbd00-0e00-401c-9eca-fa11bc7cdcac",
                                            "state_id": "9d5b5f6c-298d-4d57-893b-c57461670c6f",
                                            "name": "Nome de nota 2"
                                        },
                                        {
                                            "id": "e8de5b1f-f784-413c-9c1b-ed2d55715add",
                                            "state_id": "ad2b9a13-7e6d-442b-a41d-41f83cddf59e",
                                            "name": "Nome de nota 3"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/notas\/{id}": {
            "get": {
                "tags": [
                    "Notas"
                ],
                "summary": "Return a Nota.",
                "description": "Return a single record of Nota.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Nota id.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/NotaGet"
                                    },
                                    "example": {
                                        "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                                        "state_id": "8b8898c3-c0f3-4233-9327-034c3a416713",
                                        "name": "Nome de nota"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Notas"
                ],
                "summary": "Delete a Nota.",
                "description": "Delete a single record of Nota.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Nota id.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#\/components\/schemas\/NotaGet"
                                    },
                                    "example": {
                                        "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                                        "state_id": "6dafc499-8b70-47e4-9b49-5a9353cc2083",
                                        "name": "Nome de nota"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "schemas": {
            "PessoaCreate": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "nomeMAe": {
                        "type": "string"
                    },
                    "nomePai": {
                        "type": "string"
                    },
                    "cep": {
                        "type": "string"
                    },
                    "dataNascimento": {
                        "type": "string"
                    }
                },
                "example": {
                    "nome": "Gabriel Velezmoro",
                    "nomeMae": "nome mae",
                    "nomePai": "nome pai",
                    "cep": "88790000",
                    "dataNascimento": "02-07-1997"
                }
            },
            "PessoaList": {
                "type": "object",
                "properties": {
                    "search": {
                        "type": "string"
                    },
                    "rowsPerPage": {
                        "type": "int"
                    },
                    "page": {
                        "type": "int"
                    }
                },
                "example": {
                    "search": "",
                    "rowsPerPage": "10",
                    "page": ""
                }
            },
            "PessoaGet": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "code": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                    "code": "Uf de state",
                    "name": "Nome de state"
                }
            },
            "PessoaUpdate": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "nomeMae": {
                        "type": "string"
                    },
                    "nomePai": {
                        "type": "string"
                    },
                    "cep": {
                        "type": "string"
                    },
                    "dataNascimento": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": 5,
                    "nome": "Gabriel Velezmoro",
                    "nomeMae": "nome mae",
                    "nomePai": "nome pai",
                    "cep": "88790000",
                    "dataNascimento": "1997-02-07T02:00:00.000Z"
                }
            },
            "NotaCreate": {
                "type": "object",
                "properties": {
                    "state_id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "example": {
                    "state_id": "e09c8bef-4394-4e7d-9d25-6996c4cdce86",
                    "name": "Nome de nota"
                }
            },
            "NotaList": {
                "type": "object",
                "properties": {
                    "search": {
                        "type": "string"
                    },
                    "rowsPerPage": {
                        "type": "int"
                    },
                    "page": {
                        "type": "int"
                    }
                },
                "example": {
                    "search": "nota",
                    "rowsPerPage": "10",
                    "page": 1
                }
            },
            "NotaGet": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "state_id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                    "state_id": "b63764b1-b0f0-4b82-b0ac-f0754346f23c",
                    "name": "Nome de nota"
                }
            },
            "NotaUpdate": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "state_id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "example": {
                    "id": "da9f1c3d-3271-4b30-b729-1196e5b7402b",
                    "state_id": "2e2c5c36-ed47-4dcc-b3fb-7eb97d9f7007",
                    "name": "Nome de nota"
                }
            }
        }
    }
}